Added a TextArea component.
Testausserveri/testausserveri.fi pull request #104
Opened 2023-06-28 18:52 UTC by onnilinnala

Edit the font, width and colors.

2023-06-28 18:59 UTC, Eldemarkki requested changes

2023-06-28 18:59 UTC, Eldemarkki commented on components/TextArea/TextArea.tsx
> +const autosizeTextArea = (
This should be renamed to `useAutosizeTextArea` (or something else that starts with `use`) because it calls the `useEffect`

2023-06-28 19:28 UTC, ahnl commented
Tuli oikein kivan näkönen!

<img width="205" alt="Screenshot 2023-06-28 at 22 22 09" src="https://github.com/Testausserveri/testausserveri.fi/assets/46541386/1a173bfa-6d66-4832-87e3-5094e1e8c407">

---

Pari muutosehdotusta tekstin tyyliin:
```css
padding: 1rem;
font-family: -apple-system, BlinkMacSystemFont, Segoe UI, Roboto, Oxygen,
Ubuntu, Cantarell, Fira Sans, Droid Sans, Helvetica Neue, sans-serif;
font-size: 0.8em;
```
Kuva näillä muutoksilla:
<img width="1264" alt="Screenshot 2023-06-28 at 22 27 48" src="https://github.com/Testausserveri/testausserveri.fi/assets/46541386/98663ac4-aa7c-4ffb-8bc5-d06cdfc3ec65">

Eli käytännössä vaan tasanen padding kaikilta sivuilta ja fontti samaksi mitä leipätekstissä muualla sivulla.

Saisko nää muutokset vielä PR:ään?

2023-06-28 19:29 UTC, ahnl commented
Ja koodiki näyttää tyyliltään hyvältä, mahtava eka PR!

2023-06-29 15:01 UTC, merged

2023-06-29 15:01 UTC, ahnl commented
Kiitos kontribuutiosta!