Add more projects to docs/projects
Testausserveri/testausserveri.fi pull request #49
Opened 2022-05-18 13:52 UTC by kymppi

Added projects:
- Koululaskuri
- Abitti OpenAccess

related to: #47

2022-05-19 18:41 UTC, ahnl commented on docs/projects/Koululaskuri/README.md
> +Koululaskuri on simppeli discord webhook joka kertoo kauanko koulua on jäljellä.
Pay attention to the style of text

2022-05-19 18:42 UTC, ahnl requested changes

2022-05-19 18:42 UTC, ahnl commented on docs/projects/Koululaskuri/README.md
> +Koululaskuri on simppeli discord webhook joka kertoo kauanko koulua on jäljellä.
Please pay attention to the style of text.

2023-01-13 05:45 UTC, Esinko commented
@raikasdev Is this text correct? Please review it.

2023-01-17 12:58 UTC, raikasdev commented
It is correct, but would like it to be more "formal" for the association homepage.

2023-03-01 19:27 UTC, closed without merging